services:
  gatus:
    image: ghcr.io/twin/gatus:v5.16.0
    ports:
      - "8080:8080"
    restart: always
    volumes:
      - /etc/gatus:/config
  derp:
    image: fredliang/derper:v1.88.3
    ports:
      - "80:80"
      - "443:443"
      - "3478:3478/udp"
    environment:
      DERP_DOMAIN: "derp.bqc0n.com"

